version: '3'
services:
  python_flask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        admin_email: myemail@gmail.com
        domain: darksubs.hu
    networks:
      - web
    ports:
      - "8080:80"
    tty: true
    restart: unless-stopped

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/24